id: A63242085
title: 'The Sweet Song of Gathering Auspiciousness: A Prayer for Long Life and Name
  Offering for the Gentle Lord, Dharma Friend and Supreme Tulku Rinpoche'
type: translation
pechas:
- I044327B9
- ICC8C24CB
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:37:41.368684
  last_modified_at: 2023-01-04 11:37:41.368696
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I044327B9/71AA: '5874'
  ICC8C24CB/D030: '5874'
